### ISSUE TITLE
Minor suggestions

### ISSUE THREAD

**Issue by adityaraute** [Utkarsh299-tech/Utkarsh299-tech#1]
Here are some suggestions that I feel will help your profile look more professional.

- [x] Center the GIFs
- [x] Manage the height and width of all Stats Cards so they look better
- [x] Center the Tech Stack table.
- [x] Adjust the height and width of the images in the Tech Stack logos for uniformity.

**Comment by Utkarsh299-tech** [comment]
> Here are some suggestions that I feel will help your profile look more professional.
> 
> * [x]  Center the GIFs
> * [x]  Manage the height and width of all Stats Cards so they look better
> * [x]  Center the Tech Stack table.
> * [x]  Adjust the height and width of the images in the Tech Stack logos for uniformity.

Hey @dumbcoder7, thanks for reviewing my profile! I've done the required changes as you suggested. Please review it and suggest to me if there are more changes to be done.

**Comment by adityaraute** [comment]
I dig the new changes, well done. 👍 

I had one more suggestion, I think you should remove the `profile views` tab. It functions incorrectly and gets incremented anytime someone even refreshes the page. I would prefer the `hits` tab, but not that one. Either way, your choice.


Upon further inspection, I am not sure if the `hits` tab is a good idea either.

**Comment by Utkarsh299-tech** [comment]
> I dig the new changes, well done. 👍
> 
> I had one more suggestion, I think you should remove the `profile views` tab. It functions incorrectly and gets incremented anytime someone even refreshes the page. I would prefer the `hits` tab, but not that one. Either way, your choice.
> 
> Upon further inspection, I am not sure if the `hits` tab is a good idea either.

Thanks for your valuable feedback @dumbcoder7. As you suggested I removed the `profile views` tab. Yes, you are quite right about that tab, whenever I refresh the page there is an increase in profile views so I too thought that's quite irrelevant. And as you inspected the `hits` tab, I too think it's a good idea to remove the same. But, can you suggest to me something which I should add in place of these tabs? That would be really helpful!

**Comment by adityaraute** [comment]
Hi Utkarsh, I am myself struggling to find a good kind of tab to display stats on my README. I do have an open source tab on my profile, maybe you can pick that up? Apart from that, I don't really know sorry.

**Comment by Utkarsh299-tech** [comment]
> Hi Utkarsh, I am myself struggling to find a good kind of tab to display stats on my README. I do have an open-source tab on my profile, maybe you can pick that up? Apart from that, I don't really know sorry.

Hey Aditya, thanks for suggesting such a nice tab `open-source`. I really liked that and I picked that up. Now, my profile looks even more awesome. Thanks, mate! :)
